config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  get "about", to: "pages#about"
  resources :portfolios
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :portfolio_categories
  has_many :portfolios, through: :portfolio_categories
  
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 5, maximum: 5000}

  belongs_to :user
  has_many :portfolio_categories
  has_many :categories, through: :portfolio_categories
end

app/models/portfolio_category.rb
class PortfolioCategory < ApplicationRecord
  belongs_to :category
  belongs_to :portfolio
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :portfolios, dependent: :destroy
  has_many :categories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
    
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user
    if @category.save
      flash[:notice] = "You have successfully create a category"
      redirect_to @category    
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update
    if @category.update(category_params)
      flash[:notice] ="You have seccessfully updated your category"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
  
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  def index
    @portfolios = Portfolio.all
  end

  def new
    @portfolio = Portfolio.new
  end

  def show
    
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    @portfolio.user = current_user
    if @portfolio.save
      flash[:notice] = "You have successfully create a portfolio"
      redirect_to @portfolio      
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update
    if @portfolio.update(portfolio_params)
      flash[:notice] ="You have seccessfully updated your portfolio"
      redirect_to @portfolio
    else
      render 'edit'
    end
  end

  def destroy
    @portfolio.destroy
    
  end

  private
  def portfolio_params
    params.require(:portfolio).permit(:name, :description, category_ids: [])
  end

  def set_portfolio
    @portfolio = Portfolio.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
# frozen_string_literal: true
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    err = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <ul>#{err}</ul>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/index.html.erb
<div class="row">
  <h3 class="center-align">Category Listing </h3>
  <% @categories.each do |category| %>
    <div class="col s12 m6">
      <div class="card ">
        <div class="card-content ">
          <span class="card-title"><%= category.name %></span>
          
        </div>
        <div class="card-action">
        
        </div>
      </div>
    </div> 
    
  <% end %>
  <%= link_to '<i class="material-icons right">note</i>New'.html_safe, new_category_path, class:"waves-effect waves-light btn" %>
</div>

app/views/categories/new.html.erb
<div class="container">
<div class="row center sign-up-form">
  <div class="col s12">
    <div class="card-panel">
    <h3 class="header">New Category</h3>
      <div class="row ">
        <%= form_for(@category, html: {class: "col s12"}) do |f| %>
          <div class="row">
            <div class="input-field col s12">
              <%= f.text_field :name, placeholder: "Enter name", autofocus: true %> 
              <%= f.label :name %>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <%= f.button( '<i class="material-icons right">arrow_forward</i>Add'.html_safe , class: "waves-effect waves-light btn right") %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/categories/show.html.erb
<div class="row sign-up-form">
  <div class="col s12 m6">
    <div class="card ">
      <div class="card-content ">
        <span class="card-title">Name: <%= @category.name %></span>
        
      </div>
      <div class="card-action">
      
      <%= link_to '<i class="material-icons right">delete</i>Delete'.html_safe, category_path(@category), method: :delete, class:"waves-effect waves-light btn" %>
      </div>
    </div>
  </div>  
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer ">     
  <div class="container">
  © 2021 Code the Dream
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
  </div>

</footer>

app/views/layouts/_nav.html.erb
<header>
  <!-- Dropdown Structure -->
  <ul id="dropdown1" class="dropdown-content">
    <%= link_to "Sign up", new_user_registration_path, class: "dropdown-text" %>
    <%= link_to "Login", new_user_session_path, class: "dropdown-text" %>
    <li class="divider"></li>
    <%= link_to "Logout", destroy_user_session_path, mehtod: :delete, class: "dropdown-text" %> 
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <%= link_to "Sign up", new_user_registration_path, class: "dropdown-text" %>
    <%= link_to "Login", new_user_session_path, class: "dropdown-text" %>
    <li class="divider"></li>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-text" %> 
  </ul>
  <nav >
    <div class="container">
        <div class="nav-wrapper">
        <%= link_to "Discord", root_path, class:"brand-logo" %>        
          <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Portfolios", portfolios_path %></li>
            <!-- Dropdown Trigger -->
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
          </ul>
          <ul class="sidenav" id="mobile-demo">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Portfolios", portfolios_path %></li>
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
          </ul>
        </div>
      </div>
    </nav>
    <% flash.each do |key, message| %>
      <div class="container">
        <div class="row sign-up-form">
          <div class="col s12">
            <div class="card-panel red lighten-3" id="fade-out-target">
              <span class="text-white">      
                <%= message %>  
              </span>
            </div>
          </div>
        </div>
      </div>
    <% end %> 
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discord</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    
    <main>
      <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> Welcome About page </h1>

app/views/pages/index.html.erb
<div class="carousel">
    <a class="carousel-item" href="#one!"><%= image_tag 'carousel1.jpg' %></a>
    <a class="carousel-item" href="#two!"><%= image_tag 'carousel2.jpg' %></a>
    <a class="carousel-item" href="#three!"><%= image_tag 'carousel3.jpg' %></a>
    <a class="carousel-item" href="#four!"><%= image_tag 'carousel4.jpg' %></a>
    <a class="carousel-item" href="#five!"><%= image_tag 'carousel5.jpg' %></a>
</div>
<%= link_to 'Sign out', destroy_user_session_path, method: :delete %> 

app/views/portfolios/_form.html.erb
<%= render 'shared/errors', obj: @portfolio %>

<div class="container">
<div class="row center sign-up-form">
  <div class="col s12">
    <div class="card-panel">
    <h3 class="header"><%= @portfolio.new_record? ? "Add Portfolio" : "Edit Portfolio" %></h3>
      <div class="row ">
        <%= form_for(@portfolio, html: {class: "col s12"}) do |f| %>
          <div class="row">
            <div class="input-field col s12">
              <%= f.text_field :name, placeholder: "Enter name", autofocus: true %> 
              <%= f.label :name %>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <%= f.text_field :description, placeholder: "Enter description" %> 
              <%= f.label :description %>
            </div>
          </div>
          <div class="row">
            
            
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text } %>
            <% end %>
           
          </div>
          <div class="row">
            <div class="input-field col s12">
              <%= f.button(@portfolio.new_record? ? '<i class="material-icons right">arrow_forward</i>Add'.html_safe : '<i class="material-icons right">arrow_forward</i>Update'.html_safe, class: "waves-effect waves-light btn right") %>
            </div>
          </div>
          
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/portfolios/edit.html.erb
<h1> Edit Portfolio</h1>
<%= render 'form' %>

app/views/portfolios/index.html.erb
<div class="row">
  <h3 class="center-align">Portfolio Listing </h3>
  <% @portfolios.each do |portfolio| %>
    <div class="col s12 m6">
      <div class="card ">
        <div class="card-content ">
          <span class="card-title"><%= portfolio.name %></span>
          <p><%= portfolio.description %></p>
          
        </div>
        <div class="card-action">
        
        </div>
      </div>
    </div> 
    
  <% end %>
  <%= link_to '<i class="material-icons right">note</i>New'.html_safe, new_portfolio_path, class:"waves-effect waves-light btn" %>
</div>

app/views/portfolios/new.html.erb
<h1> New Portfolio </h1>
<%= render 'form' %>

app/views/portfolios/show.html.erb
<div class="row sign-up-form">
  <div class="col s12 m6">
    <div class="card ">
      <div class="card-content ">
        <span class="card-title">Name: <%= @portfolio.name %></span>
        <p>Description: <%= @portfolio.description %></p>
        <% if @portfolio.categories.any? %>
          <p>Categories: <%= render @portfolio.categories %></p>
        <% end %>
      </div>
      <div class="card-action">
      <%= link_to '<i class="material-icons right">create</i>Edit'.html_safe, edit_portfolio_path(@portfolio), class:"waves-effect waves-light btn" %>
      <%= link_to '<i class="material-icons right">delete</i>Delete'.html_safe, portfolio_path(@portfolio), method: :delete, class:"waves-effect waves-light btn" %>
      </div>
    </div>
  </div>  
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="container">
  <div class="row sign-up-form">
    <div class="col s12">
      <div class="card-panel red lighten-3">
        <span class="text-white">
        <strong><%= pluralize(obj.errors.count, "error") %></strong>
          prohibited your portfolio from being created
            <ul>
              <% obj.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul> 
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions' && !current_user.present?
  Already a Member?
  = link_to "Log In", new_session_path(resource_name)
  %br/

- if devise_mapping.registerable? && controller_name != 'registrations'
  Not A Member?
  = link_to "Sign Up", new_registration_path(resource_name)
  %br/

- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  Forgot
  = link_to "Password?", new_password_path(resource_name)
  %br/

- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't Receive Confirmation Instructions?",
    new_confirmation_path(resource_name)
  %br/

- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't Receive Unlock Instructions?",
    new_unlock_path(resource_name)
  %br/

- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}",
      omniauth_authorize_path(resource_name, provider)

- if controller_name == 'registrations' && current_user.present?
  = link_to "Cancel My Account", registration_path(resource_name),
    data: { confirm: "Are You Sure you want to Delete Your Account?",
    method: :delete }, class: "btn waves-effect red"